name: Release VS Code Theme

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Package the extension
        run: |
          npm install -g @vscode/vsce
          vsce package

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          tag_name: v${{ github.sha }}
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false

      - name: Upload VSIX to GitHub Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./*.vsix
          asset_name: theme.vsix
          asset_content_type: application/octet-stream

      - name: Publish to VS Code Marketplace
        env:
          VSCE_PAT: ${{ secrets.VSCE_TOKEN }}
        run: |
          vsce publish --pat $VSCE_PAT

      - name: Publish to OpenVSX
        env:
          OVSX_PAT: ${{ secrets.OVSX_TOKEN }}
        run: |
          npx ovsx publish theme.vsix -p $OVSX_PAT
